services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.7.0'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
